global:
  rbac:
    create: true
crds:
  enabled: true
  keep: true
serviceAccount:
  create: true
securityContext:
  fsGroup: 1001
  runAsUser: 1001
prometheus:
  servicemonitor:
    prometheusInstance: default
    interval: 60s
    scrapeTimeout: 30s
cainjector:
  enabled: true
